test:1.31:
  script: &test_script
  - rustc --version && cargo --version
  - cargo test --all --verbose
  image: rust:1.31

test:stable:
  script: *test_script
  image: rust:latest

test:beta:
  script: *test_script
  image: liuchong/rustup:beta

test:nightly:
  script: *test_script
  image: rustlang/rust:nightly
